Simple Lightmap editor
wootguy/bspguy pull request #29
Opened 2021-02-21 10:56 UTC by 2020karaulov2020

2021-02-21 10:58 UTC, 2020karaulov2020 commented
@wootguy  
![dEyQ3ar 1](https://user-images.githubusercontent.com/62130676/108622881-cc5e4a00-744c-11eb-8170-082e20c09f5a.jpg)
![1INfYxb 1](https://user-images.githubusercontent.com/62130676/108622883-cf593a80-744c-11eb-898e-5d55bca52445.jpg)

2021-02-21 18:47 UTC, wootguy commented
Awesome!

I tried it out on de_dust and it works well on an 8x8 lightmap near T spawn. For most other lightmaps though it's pretty broken. The lightmap gets partially filled with random data which changes when I click `Reload`, and when I draw with a red color I get blue instead, and sometimes other colors.

![image](https://user-images.githubusercontent.com/12087544/108634987-7c25be80-7431-11eb-953d-b401f8029ae9.png)

It's ok if you don't want to fix that, but please add a "WIP" text somewhere explaining these bugs (like in the face editor).

2021-02-22 03:36 UTC, 2020karaulov2020 commented
@wootguy i see IMGUI bad works with images non two multiple ?

2021-02-22 05:26 UTC, 2020karaulov2020 commented
@wootguy okay I added WIP text. + some fixes for future

2021-02-22 05:27 UTC, 2020karaulov2020 commented
@wootguy issue at imgui github https://github.com/ocornut/imgui/issues/3829

2021-02-22 05:58 UTC, 2020karaulov2020 commented
@wootguy I can enable editing lightmap for all 4 styles, but i don't know about styles. I don't see changes in game if edit other styles.

You can simple uncomment here line to enable editing for all 4 styles : https://github.com/wootguy/bspguy/blob/d4a0061478955cb6a997c2f04eadf43bbbbad8b0/src/editor/Gui.cpp#L3128

2021-02-22 06:08 UTC, wootguy requested changes
> i see IMGUI bad works with images non two multiple ?
yeah looks like it happens with NPOT textures. There might be something in the documentation about that.

2021-02-22 06:08 UTC, wootguy commented on src/gl/Texture.cpp
> +		glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
easier to edit this way 👍

2021-02-22 06:12 UTC, wootguy commented
> @wootguy I can enable editing lightmap for all 4 styles, but i don't know about styles. I don't see changes in game if edit other styles.

The other styles are for toggled lights. I don't think there are many of those in CS. It would be hard to edit those now since you can't manually toggle lights on/off in the editor.

2021-02-22 06:13 UTC, 2020karaulov2020 commented on src/editor/Gui.cpp
> +	if (ImGui::Begin("LightMap Editor (WIP)", &showLightmapEditorWidget)) {
Strange but it works even for 15x16, but not works for 11x15 11x16...) Possible WIDTH need power of two ))

2021-02-22 06:14 UTC, 2020karaulov2020 commented on src/editor/Gui.cpp
> +			}
@wootguy I don't know how to close current window))

2021-02-22 06:17 UTC, wootguy commented on src/editor/Gui.cpp
> +			}
to close set `showLightmapEditorWidget = false;`

I think it's better without the button though, and consistent with the other widgets.

2021-02-22 06:17 UTC, 2020karaulov2020 commented
> > @wootguy I can enable editing lightmap for all 4 styles, but i don't know about styles. I don't see changes in game if edit other styles.
> 
> The other styles are for toggled lights. I don't think there are many of those in CS. It would be hard to edit those now since you can't manually toggle lights on/off in the editor.

You know style names ? I can add it to lightmap editor)

2021-02-22 06:23 UTC, wootguy commented
Lights can have styles with these names:
https://twhl.info/wiki/page/light

not sure that's what you meant though.

2021-02-22 07:15 UTC, 2020karaulov2020 commented
@wootguy you missing **glPixelStorei(GL_UNPACK_ALIGNMENT, 1);** in texture code for RGB format!

2021-02-22 07:19 UTC, wootguy commented
Good find! Weird that it didn't show artifacts until now.

2021-02-22 07:20 UTC, 2020karaulov2020 commented
@wootguy all fixed and added lightmap edit for all styles))

But I found new problem ) Sometime crashes when do reloadLightmaps.

2021-02-22 07:21 UTC, 2020karaulov2020 commented
@wootguy now all works :)

2021-02-22 07:22 UTC, 2020karaulov2020 commented
![1PB6Knq 1](https://user-images.githubusercontent.com/62130676/108675420-d38e6200-74f7-11eb-9579-fc481696b18c.png)

2021-02-22 07:28 UTC, 2020karaulov2020 commented
@wootguy may be need add pixel alignment 1 byte for any texture format ?

2021-02-22 07:35 UTC, 2020karaulov2020 commented on src/editor/Gui.cpp
> +	if (ImGui::Begin("LightMap Editor (WIP)", &showLightmapEditorWidget)) {
Fixed)

2021-02-22 07:35 UTC, 2020karaulov2020 commented on src/gl/Texture.cpp
> +		glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
I think yes

2021-02-22 07:42 UTC, 2020karaulov2020 commented on src/editor/Gui.cpp
> +			}
Ok

2021-02-22 07:42 UTC, wootguy commented
That fixed all the problems I saw earlier. Some comments on the window:
* The labels don't really make sense. All lightmaps could be considered "Light enabled". Maybe go with "Light 0", "Light 1", "Light 2", "Light 3".
* The lightmap size will be the same for all layers, so no need to show the size for all of them.
* would be nice to be able to resize the window to show the color picker without scrolling.

> may be need add pixel alignment 1 byte for any texture format ?

it's only needed for RGB textures. The default value of 4 is faster for RGBA.

2021-02-22 07:42 UTC, 2020karaulov2020 commented on src/editor/Gui.cpp
> +					if (offset > currentlightMap[i]->width * currentlightMap[i]->height * 3)
added

2021-02-22 08:20 UTC, 2020karaulov2020 commented
@wootguy now all fixed ?))

Added turn off light in lightmap editor, and return back texture aligment for non RGB.

2021-02-22 08:28 UTC, 2020karaulov2020 commented
**All checked and should work now!**

2021-02-22 08:37 UTC, wootguy commented
Nice that you you can toggle light styles now. I've got ideas for improvement, but it's working well enough to merge.

![image](https://user-images.githubusercontent.com/12087544/108682629-7343f400-74e8-11eb-91ea-b6b07b36610d.png)

2021-02-22 08:38 UTC, merged